### ISSUE TITLE
Error: Could not find or load main class org.jooq.util.GenerationTool

### ISSUE THREAD

**Issue by emssik** [sean8223/jooq-sbt-plugin#16]
Hi,

I have this error, after change jooqVersion to 3.7.0.

Extra info:

java.lang.RuntimeException: Failed with return code: 1
    at scala.sys.package$.error(package.scala:27)
    at scala.Predef$.error(Predef.scala:142)
    at JOOQPlugin$.JOOQPlugin$$executeJooqCodegen(JOOQPlugin.scala:223)
    at JOOQPlugin$.JOOQPlugin$$executeJooqCodegenIfOutOfDate(JOOQPlugin.scala:209)
    at JOOQPlugin$$anonfun$8.apply(JOOQPlugin.scala:87)
    at JOOQPlugin$$anonfun$8.apply(JOOQPlugin.scala:86)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](loans/compile:managedSources) Failed with return code: 1

Regards

Daniel Roziecki

**Comment by emssik** [comment]
Version 1.5 is ok, 1.6 is not.

**Comment by yaroslav-ulanovych** [comment]
Same shit.

**Comment by murphyslaw** [comment]
:+1:

**Comment by kusamakura** [comment]
I solved this by manually adding the jooq-codegen dependency into my classpath, e.g.

``` scala
libraryDependencies += "org.jooq" % "jooq-codegen" % jooqVersion
```

I'm using this plugin's version 1.6 and jooq 3.7.2, as well as the template config option.
